#!/usr/bin/env python3
f = open(r'C:\Users\33589\Downloads\b2btrade-agent\src\index.js', 'rb')
d = f.read()
f.close()
lines = d.split(b'\n')
# Fix lines 385, 386, 387 (0-indexed)
lines[385] = "      console.log('  ' + chalk.green('4') + '   CRM 客户仪表盘');".encode('utf-8')
lines[386] = "      console.log('  ' + chalk.green('5') + '   HS编码查询');".encode('utf-8')
lines[387] = "      console.log('  ' + chalk.green('0') + '   退出');".encode('utf-8')
d = b'\n'.join(lines)
f = open(r'C:\Users\33589\Downloads\b2btrade-agent\src\index.js', 'wb')
f.write(d)
f.close()
print('done')
